"""Qwen3-TTS engine for English + Chinese TTS.

Uses THREE models:
  - Qwen3-TTS-12Hz-0.6B-CustomVoice:   9 preset speakers via generate_custom_voice
  - Qwen3-TTS-12Hz-1.7B-VoiceDesign:   designed voices via generate_voice_design
  - Qwen3-TTS-12Hz-1.7B-Base:          voice clone via generate_voice_clone

All models loaded lazily on first use (class-level cache).
Chinese TTS is overridden to use Qwen natively (replaces edge-tts).
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace", line_buffering=True)
    except Exception:
        pass  # stdout may be redirected/captured (web/pytest) — reconfigure unavailable

# SoX (installed via conda) may not be in PATH for the web process
_conda_bin = r"G:\software\miniconda3\Library\bin"
if sys.platform == "win32" and _conda_bin not in os.environ.get("PATH", ""):
    os.environ["PATH"] = _conda_bin + os.pathsep + os.environ.get("PATH", "")

_PARENT = str(Path(__file__).parent.resolve())
if _PARENT not in sys.path:
    sys.path.insert(0, _PARENT)

from tts_engine import (TTSEngine, _split_sentences, _rate_to_speed,
                        _same_gender_ranks, _gender_default, _resolve_mode_defaults)

# --- 9 preset speakers ---
QWEN_SPEAKERS = [
    {"name": "Vivian",    "desc": "明亮年轻女声 (中文)", "gender": "female", "lang": "zh"},
    {"name": "Serena",     "desc": "温暖柔和女声 (中文)", "gender": "female", "lang": "zh"},
    {"name": "Uncle_Fu",   "desc": "沉稳成熟男声 (中文)", "gender": "male",   "lang": "zh"},
    {"name": "Dylan",      "desc": "年轻北京男声 (中文)", "gender": "male",   "lang": "zh"},
    {"name": "Eric",       "desc": "活泼成都男声 (中文)", "gender": "male",   "lang": "zh"},
    {"name": "Ryan",       "desc": "活力节奏男声 (英文)", "gender": "male",   "lang": "en"},
    {"name": "Aiden",      "desc": "阳光美式男声 (英文)", "gender": "male",   "lang": "en"},
    {"name": "Ono_Anna",   "desc": "俏皮日语女声 (日语)", "gender": "female", "lang": "ja"},
    {"name": "Sohee",      "desc": "温暖韩语女声 (韩语)", "gender": "female", "lang": "ko"},
]

_PRESET_NAMES = {s["name"] for s in QWEN_SPEAKERS}

# --- Built-in VoiceDesign voices (fill the English-female gap) ---
# Generated by Qwen3-TTS-12Hz-1.7B-VoiceDesign via generate_voice_design.
# instruct combines voice timbre + learner-friendly delivery.
DESIGNED_VOICES_BUILTIN = [
    {"name": "Ella", "gender": "female", "lang": "en", "builtin": True,
     "desc": "温暖友好美式女声 (英文)",
     "instruct": "Speak in a warm, friendly young American female voice with a "
                 "mid-range pitch and a relaxed, moderate pace. Sound "
                 "conversational and expressive, like a native speaker talking "
                 "with a student. Articulate words clearly without "
                 "over-pronouncing them, with natural pauses between sentences."},
    {"name": "Maya", "gender": "female", "lang": "en", "builtin": True,
     "desc": "明亮活力美式女声 (英文)",
     "instruct": "Speak in a bright, energetic young American female voice, "
                 "lively and expressive with natural intonation, at a moderate "
                 "pace that English learners can comfortably follow."},
    {"name": "Chloe", "gender": "female", "lang": "en", "builtin": True,
     "desc": "轻柔温和女声 (英文)",
     "instruct": "Speak in a soft, gentle, calm female voice with a slightly "
                 "lower pitch. Sound patient and approachable with a smooth "
                 "delivery at a relaxed, learner-friendly pace."},
    {"name": "Hazel", "gender": "female", "lang": "en", "builtin": True,
     "desc": "成熟清晰女声 (英文/旁白)",
     "instruct": "Speak in a mature, confident American female voice with clear "
                 "articulation, suitable for narration. Keep a steady, engaging "
                 "pace with gentle emphasis on key phrases."},
]

# Default auto-assign by gender (for non-library characters)
_DEFAULT_MALE = "Ryan"
_DEFAULT_FEMALE = "Vivian"
_DEFAULT_HOST_FEMALE = "Serena"

# 预设名 → 语言（中文台词回退校正用：英文/日/韩预设说中文带外语口音）
_PRESET_LANG = {s["name"]: s["lang"] for s in QWEN_SPEAKERS}

# 中文台词的默认性别预设（与 MOSS 的 Junhao/Xiaoyu 策略对齐）
_ZH_DEFAULT_MALE = "Dylan"
_ZH_DEFAULT_FEMALE = "Vivian"

# 按模式分套默认音色的内置兜底（configs/qwen_voice_config.json 的 modes 键同名）
QWEN_VOICE_DEFAULTS = {
    "default_male": _DEFAULT_MALE,
    "default_female": _DEFAULT_FEMALE,
    "default_host_female": _DEFAULT_HOST_FEMALE,
    "default_host_male": _DEFAULT_MALE,  # 主持人默认男声（主持人性别为男时用；默认与第一男声相同，可自行错开）
    "default_male2": "Aiden",
    "default_female2": "Ella",
    "default_male3": "Aiden",   # en 男预设仅 Ryan/Aiden，第三默认回退同第二（UI 可改绑自定义/设计音色）
    "default_female3": "Maya",
    "default_male_zh": _ZH_DEFAULT_MALE,
    "default_female_zh": _ZH_DEFAULT_FEMALE,
    "default_male_zh2": "Eric",
    "default_female_zh2": "Serena",
}


# ---------------------------------------------------------------------------
# Config file helpers
# ---------------------------------------------------------------------------

def _voice_config_path() -> Path:
    return Path(__file__).parent.parent / "configs" / "qwen_voice_config.json"


def _load_voice_config() -> dict:
    """Load qwen_voice_config.json, return defaults if not exists."""
    defaults = {
        "default_male": _DEFAULT_MALE,
        "default_female": _DEFAULT_FEMALE,
        "default_host_female": _DEFAULT_HOST_FEMALE,
        "custom_voices": [],
        "designed_voices": [],
        "candidate_voices": [],  # LLM 随机生成、待试听挑选的候选设计音色
    }
    path = _voice_config_path()
    if path.exists():
        try:
            saved = json.loads(path.read_text(encoding="utf-8"))
            # update 而非逐已知键回拷：保留未知键（如按模式分套的 modes）
            defaults.update(saved)
        except (json.JSONDecodeError, OSError):
            pass
    return defaults


def get_all_voices() -> list[dict]:
    """Return preset + designed + custom voices for UI dropdowns.

    同名去重：设计音色冻结为克隆音色后（custom_voices 同名存在），
    不再以设计音色身份重复出现（冻结版为准）。
    """
    config = _load_voice_config()
    custom_names = {cv["name"] for cv in config.get("custom_voices", [])}

    voices = list(QWEN_SPEAKERS)
    for dv in DESIGNED_VOICES_BUILTIN:
        if dv["name"] in custom_names:
            continue
        voices.append({
            "name": dv["name"],
            "desc": dv["desc"],
            "gender": dv["gender"],
            "lang": dv["lang"],
            "designed": True,
            "builtin": True,
        })
    for dv in config.get("designed_voices", []):
        if dv["name"] in custom_names:
            continue
        voices.append({
            "name": dv["name"],
            "desc": dv.get("description", ""),
            "gender": dv.get("gender", ""),
            "lang": dv.get("language", "en"),
            "designed": True,
            "builtin": False,
        })
    for cv in config.get("custom_voices", []):
        voices.append({
            "name": cv["name"],
            "desc": cv.get("description", ""),
            "gender": cv.get("gender", ""),
            "lang": cv.get("language", ""),
            "custom": True,
            # 冻结自设计音色（保存时自动生成的克隆版，音色稳定）
            "frozen": cv.get("frozen_from") == "designed",
        })
    return voices


def get_designed_voice_meta(name: str) -> dict | None:
    """Look up a designed voice (builtin → user-designed → candidate). None if not found.

    候选音色（candidate_voices，LLM 随机生成待挑选）与设计音色同构，
    也走 VoiceDesign 模型合成，故一并在此解析（试听端点无需注册即可用）。
    """
    for dv in DESIGNED_VOICES_BUILTIN:
        if dv["name"] == name:
            return dv
    config = _load_voice_config()
    for dv in config.get("designed_voices", []):
        if dv["name"] == name:
            return dv
    for cv in config.get("candidate_voices", []):
        if cv["name"] == name:
            return cv
    return None


def get_custom_voice_meta(name: str) -> dict | None:
    """Look up a custom voice by name. Returns None if not found."""
    config = _load_voice_config()
    for cv in config.get("custom_voices", []):
        if cv["name"] == name:
            return cv
    return None


def pick_zh_preset_fallback(name: str, gender: str = "", rank: int = 0,
                            structure: str | None = None) -> str:
    """中文合成音色回退校正 + 同性别错开。

    绑定的预设为外语（en/ja/ko）时换成中文性别预设；rank 为同性别分组序号
    （0=第一默认, 1=第二默认），避免同性别两角色中文台词撞音色。
    克隆/设计音色不受影响（非 _PRESET_LANG 成员，原样返回）。
    """
    if _PRESET_LANG.get(name, "zh") == "zh":
        return name
    defaults = _resolve_mode_defaults(_load_voice_config(), structure,
                                      QWEN_VOICE_DEFAULTS)
    if (gender or "").lower() == "male":
        return _gender_default(defaults, "default_male_zh", rank)
    return _gender_default(defaults, "default_female_zh", rank)


def gender_default_ranks(script: dict) -> dict[str, int]:
    """char_a/b/c 未绑定 qwen 音色者的同性别分组序号（0=第一默认,1=第二,2=第三）."""
    return _same_gender_ranks([
        (key, (script.get(f"{key}_gender") or "").lower(),
         bool((script.get(f"{key}_qwen_speaker") or "").strip()))
        for key in ("char_a", "char_b", "char_c")
    ])


def build_qwen_voice_map(script: dict, structure: str | None = None) -> dict:
    """Build voice_map for Qwen-TTS.

    Priority: script['char_X_qwen_speaker'] (from library) > auto by gender.
    Default speakers come from qwen_voice_config.json 按模式分套默认音色：
    未绑定的同性别角色依次取第一/第二/第三默认（char_a→char_b→char_c），
    性别不同时各自取第一默认。structure 决定用哪个模式的默认套
    （缺省读 script['structure']，再兜底 original）。
    """
    if not structure:
        structure = script.get("structure") or "original"
    defaults = _resolve_mode_defaults(_load_voice_config(), structure,
                                      QWEN_VOICE_DEFAULTS)
    ranks = gender_default_ranks(script)

    voice_map = {}
    for key in ["char_a", "char_b", "char_c", "char_d", "char_e", "host"]:
        # Priority 1: qwen_speaker from script (set by library binding)
        speaker = script.get(f"{key}_qwen_speaker", "")
        if speaker:
            voice_map[key] = speaker
            continue
        # Priority 2: auto by gender (+ 同性别错开)
        gender = script.get(f"{key}_gender", "").lower()
        if not gender:
            continue
        if key == "host":
            voice_map[key] = (defaults["default_host_female"] if gender == "female"
                              else _gender_default(defaults, "default_host_male", 0))
        else:
            base = "default_female" if gender == "female" else "default_male"
            voice_map[key] = _gender_default(defaults, base, ranks.get(key, 0))
    return voice_map


_DEFAULT_INSTRUCT = (
    "Speak naturally and clearly in a warm, friendly American English voice. "
    "Use a relaxed, slow-to-moderate pace that allows English learners to "
    "comfortably understand and follow the story. Keep the delivery "
    "conversational and expressive, like a native speaker telling a simple "
    "story to a student. Articulate words clearly without over-pronouncing "
    "them. Use natural pauses between sentences and slightly longer pauses "
    "before or after important phrases. Give gentle emphasis to useful "
    "vocabulary and expressions, while keeping the overall delivery smooth "
    "and engaging. Sound patient, approachable, and encouraging. Avoid a "
    "robotic, overly slow, overly dramatic, or textbook-like delivery."
)


class QwenTTSEngine(TTSEngine):
    """Qwen3-TTS engine: preset speakers + designed voices + voice clone.

    Uses three models:
      - CustomVoice model for preset speakers (generate_custom_voice)
      - VoiceDesign model for designed voices (generate_voice_design)
      - Base model for voice clone (generate_voice_clone)

    Inherits _loudnorm, get_duration from TTSEngine.
    Overrides synth_english and synth_chinese.
    """

    _custom_voice_model = None
    _voicedesign_model = None
    _base_model = None
    _device = None

    def __init__(self, model_path: str, device: str = "cuda:0",
                 base_model_path: str = "",
                 voicedesign_model_path: str = ""):
        self._model_path = model_path      # CustomVoice model
        self._base_model_path = base_model_path  # Base model for voice clone
        self._voicedesign_model_path = voicedesign_model_path  # VoiceDesign model
        QwenTTSEngine._device = device

    @classmethod
    def _get_custom_voice_model(cls, model_path: str, device: str):
        """Lazy-init CustomVoice model (class-level cache)."""
        if cls._custom_voice_model is None:
            # Ensure HF_ENDPOINT is set before any HF operations
            if "HF_ENDPOINT" not in os.environ and sys.platform == "win32":
                os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
            import torch
            from qwen_tts import Qwen3TTSModel
            resolved = str(Path(model_path).resolve())
            print(f"  [QwenTTS] Loading CustomVoice model from {resolved} on {device}...")
            cls._custom_voice_model = Qwen3TTSModel.from_pretrained(
                resolved,
                device_map=device,
                dtype=torch.bfloat16,
            )
            print(f"  [QwenTTS] CustomVoice model loaded.")
        return cls._custom_voice_model

    @classmethod
    def _get_voicedesign_model(cls, voicedesign_model_path: str, device: str):
        """Lazy-init VoiceDesign model for designed voices (class-level cache)."""
        if cls._voicedesign_model is None:
            # Ensure HF_ENDPOINT is set before any HF operations
            if "HF_ENDPOINT" not in os.environ and sys.platform == "win32":
                os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
            import torch
            from qwen_tts import Qwen3TTSModel
            resolved = str(Path(voicedesign_model_path).resolve())
            print(f"  [QwenTTS] Loading VoiceDesign model from {resolved} on {device}...")
            cls._voicedesign_model = Qwen3TTSModel.from_pretrained(
                resolved,
                device_map=device,
                dtype=torch.bfloat16,
            )
            print(f"  [QwenTTS] VoiceDesign model loaded.")
        return cls._voicedesign_model

    @classmethod
    def _get_base_model(cls, base_model_path: str, device: str):
        """Lazy-init Base model for voice clone (class-level cache)."""
        if cls._base_model is None:
            # Ensure HF_ENDPOINT is set before any HF operations
            if "HF_ENDPOINT" not in os.environ and sys.platform == "win32":
                os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"
            import torch
            from qwen_tts import Qwen3TTSModel
            resolved = str(Path(base_model_path).resolve())
            print(f"  [QwenTTS] Loading Base model from {resolved} on {device}...")
            cls._base_model = Qwen3TTSModel.from_pretrained(
                resolved,
                device_map=device,
                dtype=torch.bfloat16,
            )
            print(f"  [QwenTTS] Base model loaded.")
        return cls._base_model

    def _synth(self, text: str, voice: str, language: str,
               out_path: str, rate: str) -> float:
        """Core synthesis: split sentences, generate, concat, convert, loudnorm.

        Preset speakers   -> CustomVoice model + generate_custom_voice
        Designed voices   -> VoiceDesign model + generate_voice_design
        Custom clone      -> Base model + generate_voice_clone
        """
        import numpy as np
        import soundfile as sf

        Path(out_path).parent.mkdir(parents=True, exist_ok=True)

        # Determine synthesis mode.
        # 查找顺序 custom → designed：冻结后的音色以克隆（ref_audio 锚定）为准，
        # 否则内置设计音色（如 Ella）冻结后仍会走设计模式，音色继续漂移。
        is_preset = voice in _PRESET_NAMES
        is_designed = False
        designed_meta = None
        custom_meta = None
        if not is_preset:
            custom_meta = get_custom_voice_meta(voice)
            if not custom_meta:
                designed_meta = get_designed_voice_meta(voice)
                if designed_meta:
                    is_designed = True
                else:
                    print(f"  [QwenTTS] Unknown voice '{voice}', falling back to {_DEFAULT_MALE}")
                    voice = _DEFAULT_MALE
                    is_preset = True

        # Load the appropriate model
        if is_preset:
            model = self._get_custom_voice_model(self._model_path, self._device)
        elif is_designed:
            if not self._voicedesign_model_path:
                raise RuntimeError(
                    "Designed voices require the VoiceDesign model. "
                    "Please set qwen_voicedesign_model_path in configuration."
                )
            model = self._get_voicedesign_model(self._voicedesign_model_path, self._device)
        else:
            if not self._base_model_path:
                raise RuntimeError(
                    "Voice clone requires the Base model. "
                    "Please set qwen_base_model_path in configuration."
                )
            model = self._get_base_model(self._base_model_path, self._device)

        all_audio = []
        sr = None

        for sentence in _split_sentences(text):
            sentence = sentence.strip()
            if not sentence:
                continue
            try:
                if is_preset:
                    wavs, sr = model.generate_custom_voice(
                        text=sentence,
                        language=language,
                        speaker=voice,
                        instruct=_DEFAULT_INSTRUCT,
                    )
                elif is_designed:
                    wavs, sr = model.generate_voice_design(
                        text=sentence,
                        language=language,
                        instruct=designed_meta["instruct"],
                    )
                else:
                    wavs, sr = model.generate_voice_clone(
                        text=sentence,
                        language=language,
                        ref_audio=custom_meta["ref_audio"],
                        ref_text=custom_meta["ref_text"],
                    )
                if wavs and len(wavs) > 0:
                    all_audio.append(wavs[0])
            except Exception as e:
                print(f"    [QwenTTS skip] {sentence[:40]}: {e}")

        if not all_audio:
            raise RuntimeError(f"Qwen-TTS produced no audio for: {text[:50]}")

        final_audio = all_audio[0] if len(all_audio) == 1 else np.concatenate(all_audio)

        # Write WAV, convert to MP3 with atempo speed adjustment
        wav_path = out_path.replace('.mp3', '_tmp.wav')
        sf.write(wav_path, final_audio, sr)

        speed = _rate_to_speed(rate)
        af = f"atempo={speed:.4f}" if 0.5 <= speed <= 2.0 and speed != 1.0 else "anull"
        subprocess.run(
            ["ffmpeg", "-y", "-i", wav_path,
             "-af", af,
             "-c:a", "libmp3lame", "-b:a", "128k",
             "-ar", "24000", "-ac", "1", out_path],
            check=True, capture_output=True
        )
        os.remove(wav_path)

        self._loudnorm(out_path)
        return self.get_duration(out_path)

    def synth_english(self, text: str, voice: str, out_path: str,
                      rate: str = "+0%") -> float:
        """Synthesize English text with Qwen3-TTS."""
        return self._synth(text, voice, "english", out_path, rate)

    def synth_chinese(self, text: str, voice: str, out_path: str,
                      rate: str = "-10%", max_retries: int = 5,
                      timeout: int = 30) -> float:
        """Synthesize Chinese text with Qwen3-TTS (native Chinese support)."""
        return self._synth(text, voice, "chinese", out_path, rate)
